<!-- Script for fixing the position of the datepickers in product edit page for advanced pricing, this script should be removed when Magento fixes them  -->
<script>
    require(['jquery', 'jquery/ui'], function($){
        $(document).ready(function(){
            if(window.location.pathname.includes('/admin/catalog/product/edit/id')){
                let modalButtons;
                $(document).on('mouseover','.product_form_product_form_advanced_pricing_modal .ui-datepicker-trigger', function(){
                    if(modalButtons){
                        return
                    }else {
                        const datePicker = document.querySelector('#ui-datepicker-div');
                        modalButtons = document.querySelectorAll('.product_form_product_form_advanced_pricing_modal .ui-datepicker-trigger');

                        modalButtons.forEach(btn => btn.addEventListener('click',function(){
                            datePicker.style.top = `${btn.offsetTop + datePicker.clientHeight - 70}px`
                        }));
                    }
                })
            }
        })
    });
</script>
